spring.application.name=Springactuator
server.port=8082
#Enable actuator endpoint
management.endpoints.web.exposure.include=health, info, metrics
#add app info
management.info.env.enabled=true
info.app.name=Actuator Demo App
info.app.version=1.0
info.app.desrition=simple actuator